Update cron documentation to include Spring formatting
microcks/microcks.github.io pull request #6
Opened 2021-08-30 21:56 UTC by essential-randomness

I completely removed the Wikipedia link as that specifically discusses the Unix format and will cause confusion. Instead, I swapped it with a link to the Spring documentation.

2021-09-08 07:52 UTC, lbroudoux requested changes
Please find another link 😉

2021-09-08 07:52 UTC, lbroudoux commented on documentation/using/importers/index.html
> +<p>The scheduling interval can be globally configured for all the Jobs. It is a global setting and not a per-Job one. This is achieved through the <code>services.update.interval</code> property in th
I'm not a big fan of having a link to Oracle documentation... you were mentioning Spring documentation in your comment. I've found this link to be helpful: https://spring.io/blog/2020/11/10/new-in-spring-5-3-improved-cron-expressions
What do you think?

2021-09-08 07:55 UTC, lbroudoux commented
Thanks for the PR and sorry for little delay.

Also, sorry to bother you but this is the wrong repo... We use https://github.com/microcks/microcks.io that is Markdown content to generate and commit automatically on this repo. Would you mind reapplying to this repo? Namely on the https://github.com/microcks/microcks.io/blob/master/content/documentation/using/importers.md file.

I know it could be boring and I can do for you if you prefer.

2026-01-19 18:58 UTC, yada commented
Wrong repo and fixed here: https://github.com/microcks/microcks.io/pull/451

2026-01-19 18:58 UTC, closed without merging